### ISSUE TITLE
maxpool size is 63x31

### ISSUE THREAD

**Issue by marvis** [nwojke/deep_sort#10]
Hi nwojke，

I find that after the maxpool the feature map size becomes 63x31 instead of 64x32. I guess after conv2d with stride 2 the size becomes 32x16 as expected. I wonder is it correct running in the case of abnormal size?

**Comment by nwojke** [comment]
I have added a comment to the corresponding [code line](https://github.com/nwojke/deep_sort/blob/master/generate_detections.py#L125); Closing this for now.
