### ISSUE TITLE
traning model on my own dataset 

### ISSUE THREAD

**Issue by meriambdd** [nwojke/deep_sort#100]
thank you so much for sharing this project. how can i train the model on my own data set please

**Comment by songjunqianli** [comment]
so,have you trained the model on your own data set？

**Comment by duyanfang123** [comment]
hello,have you trained the model on your own data set??? I meet this problem too

**Comment by PoonamZ** [comment]
@meriambdd @songjunqianli @duyanfang123  You got the solution for this issues?

**Comment by nwojke** [comment]
Sorry for the late reply. Have a look at our [sister repository](https://github.com/nwojke/cosine_metric_learning) for training code. I am closing the issue. You might re-open with specific questions.
