### ISSUE TITLE
Automatic coordinate update??

### ISSUE THREAD

**Issue by linzhi123** [nwojke/deep_sort#104]
Excuse me, my idea is to give a coordinate area at the beginning, then it will automatically track this coordinate area and update the coordinates? Can this code be implemented?

**Comment by nwojke** [comment]
Let me throw in a pointer to some relevant [literature](openaccess.thecvf.com/content_cvpr_2018/papers/Li_High_Performance_Visual_CVPR_2018_paper.pdf). There are also [open source implementations](https://github.com/huanglianghua/siamrpn-pytorch) available. Maybe this or a similar approach would be better suited.
