### ISSUE TITLE
Can I use this code for vehicle counting

### ISSUE THREAD

**Issue by Akhtar303nu** [nwojke/deep_sort#105]
Hey guys 
Can I use this code to count more than one class like at a same time I want to count car,bus,motorbyce
generally to count the vehicle(car,bus,motorbyce)
Thanks

**Comment by duyanfang123** [comment]
how to do this ?Do you Know?

**Comment by Akhtar303nu** [comment]
@duyanfang123 https://github.com/Qidian213/deep_sort_yolov3

**Comment by nwojke** [comment]
* You will need a different feature descriptor or even multiple (one per class). Our code for training the appearance descriptor is [online](https://github.com/nwojke/cosine_metric_learning).
* Then you could run one separate tracker instance for each object class and merge the results.

Please re-open if you have specific questions about the code base.
