### ISSUE TITLE
Download link for the checkpoint and model not working 

### ISSUE THREAD

**Issue by sheetalreddy** [nwojke/deep_sort#109]
Hi , 
The below link is not working . Can you please upload the model and checkpoint in the repo.

https://owncloud.uni-koblenz.de/owncloud/s/f9JB0Jr7f3zzqs8

**Comment by nwojke** [comment]
The link has been updated.

**Comment by antocapp** [comment]
Hello @nwojke, where I can find the link for downloading the model? Thanks
