### ISSUE TITLE
ask for the deep_sort weights 

### ISSUE THREAD

**Issue by louxy126** [nwojke/deep_sort#110]
@nwojke ,Hi
the deep_sort weights  provided by you in [https://github.com/bendidi/Tracking-with-darkflow](url)or [https://owncloud.uni-koblenz.de/owncloud/s/f9JB0Jr7f3zzqs8?path=/resources](url) is cancelled, could you upload a new one?
or anybody can share it with louxy126@126.com ,Thanks!

**Comment by nwojke** [comment]
The link has been updated.
