### ISSUE TITLE
Detect pedestrians realtime

### ISSUE THREAD

**Issue by StanlyHardy** [nwojke/deep_sort#12]
Can you point me in a direction to track pedestrians in realtime basis?

**Comment by nwojke** [comment]
Not sure, maybe [this](https://github.com/endernewton/tf-faster-rcnn) tensorflow implementation of Faster RCNN is a good start. I haven't tried it, though. YOLO is also popular, @bendidi has used it in [Issue 13](https://github.com/nwojke/deep_sort/issues/13), he might be able to share some info on which implementation he has used.

**Comment by tonmoyborah** [comment]
Hi @bendidi , great work. I don't want real time but want more accurate predictions, so YOLO is not the best choice for me given faster rcnn gives better detection. Have you tried using deep sort with faster rcnn or anything else?

**Comment by Qidian213** [comment]
I combined deep_sort and yolov3 ,it can tracking real-time use my laptop's camera
you can just change the videocapture(0) to videcapture("video path")
https://github.com/Qidian213/deep_sort_yolov3

**Comment by MounirB** [comment]
Hello everyone,
Can someone explain to me the meaning of the 7th column in the **det.txt** files of MOT16, this value is after the frame index, and the bounding boxes ? Its values are of float type and seem to vary between ~3 and -1. I am not sure if the confidence score can vary this way...
I didn't find an explanation [here](https://motchallenge.net/instructions/)
