### ISSUE TITLE
Where is the file MOT16-06.npy in nwojke/deep_sort?

### ISSUE THREAD

**Issue by simlexiaowan** [nwojke/deep_sort#124]
Where is the file MOT16-06.npy in nwojke/deep_sort?

**Comment by lan2720** [comment]
The same question.

**Comment by PoonamZ** [comment]
The Installation section from deepsort repo given the link for the checkpoint files. 
From that you can download detections directory. ./detections/MOT16_POI_test/MOT16-06.npy this is the path for  MOT16-06.npy .

**Comment by nwojke** [comment]
[Here](https://drive.google.com/drive/folders/1qNWOpUtKG8GqEiL-LbBdXyvifUtcbOvc).

Please re-open if the problem is not solved.
