### ISSUE TITLE
Store tracking id result

### ISSUE THREAD

**Issue by AngelababyTing** [nwojke/deep_sort#126]
Hello, 
I want to know,whether if I can store the tracking id result with the tracking video? 
Please help me how to do? 
Thank you so much.

**Comment by PoonamZ** [comment]
@AngelababyTing  Have you got any answer for your que ? Please can you comment it if you have any ?

**Comment by Clara85** [comment]
https://github.com/nwojke/deep_sort/blob/53ee00b894c57483aba293894b2fd8ff91cac009/deep_sort_app.py#L181 @AngelababyTing @PoonamZ

**Comment by nwojke** [comment]
The [deep_sort_app](https://github.com/nwojke/deep_sort/blob/master/deep_sort_app.py#L210) stores results in a text file in [MOT Challenge](https://www.motchallenge.net) format. I hope this helps.

**Comment by nwojke** [comment]
I close this ticket, re-open if the problem is not solved.
