### ISSUE TITLE
how to save output to a video?

### ISSUE THREAD

**Issue by VellalaVineethKumar** [nwojke/deep_sort#131]

**Comment by nwojke** [comment]
This should be fairly simple to accomplish. Have a look at the internals of [show_results.py](https://github.com/nwojke/deep_sort/blob/master/show_results.py#L15). The ``run`` function has a parameter ``video_filename`` which you may set to something like ``output.mp4`` to generate a video. Or you use [generate_videos.py](https://github.com/nwojke/deep_sort/blob/master/generate_videos.py) and adapt it to your needs.

Let me know if you have specific questions.

**Comment by VellalaVineethKumar** [comment]
Thank you that worked

**Comment by anzy0621** [comment]
@VellalaVineethKumar what are the command line arguments you gave to get the output video? I have been trying to get it working but it does not work. Can you tell me what is the command line arguments you've given??? 
example of what I've been using: python generate_videos.py --mot_dir=./vehicles/test --result_dir=./output/ --output_dir=./videos

1. does result_dir have to be a folder or the tracking result which is a text file?

**Comment by kaikaizhu** [comment]
@anzy0621
I meet the same problem.How to fix it?
python generate_videos.py --mot_dir=./vehicles/test --result_dir=./output/ --output_dir=./videos
