### ISSUE TITLE
evaluate 

### ISSUE THREAD

**Issue by ss199302** [nwojke/deep_sort#134]
@nwojke  I tried to use MOT website to evaluate the tracking results, but when I registered my account, the website item did not know what to write, and this error occurred."Email domain hotmail.com not accepted. You have either used a generic email like hotmail or 163.com, or your domain already exists in our database. Please fill out this form to request a registration."can you tell me why?thanks.

**Comment by nwojke** [comment]
Hi ss199302, unfortunately I am not associated with the MOT Challenge benchmark team. Please get directly in contact with them.

I'll close this issue, as your question is not directly related to our code.
