### ISSUE TITLE
gate cost matrix correct?

### ISSUE THREAD

**Issue by dummynope** [nwojke/deep_sort#135]
hi,
is the following line really correct?
 cost_matrix[cost_matrix > max_distance] = max_distance + 1e-5

The comment says:
 max_distance : float
        Gating threshold. Associations with cost larger than this value are
        disregarded.

So it should be:
cost_matrix[cost_matrix > max_distance] = INFTY_COST 

Or where is my misconception?

**Comment by Arsapol** [comment]
Maybe you can find your answer below. (#84 )

> [The function](https://github.com/nwojke/deep_sort/blob/master/deep_sort/linear_assignment.py#L144) replaces the cost of all invalid assignments with a constant. An assignment can be invalid because the appearance feature distance is larger than a threshold or because the measurement is outside of the gate, i.e., the region where the track is expected with a certain confidence based on Kalman filtering.
> 
> This is done because we don't want a notion of _more or less_ invalid in the assignment problem; each invalid assignment should be weighted equally.
> 
> What I found interesting is that the cost is set to _INF, or `1e+05`. I'd say this is a bug and should be changed to `threshold + EPSILON` where threshold is the gating threshold and `EPSILON` is a small number.
> 
> With respect to your investigation, I am not sure if I understand you correctly. If you have changed the threshold of the appearance feature to _INF but you still get ID swaps then it could be the motion component which is causing the swap. You might want to add [this line](https://github.com/nwojke/deep_sort/blob/master/application_util/visualization.py#L132) to visualize the Kalman filter gate of the position.

**Comment by nwojke** [comment]
Just one thing to add (from #84) about the _INF vs EPSILON discussion: I think the implementation is good as it is. When the linear assignment problem is solved in ``min_cost_matching()``, any cost larger than the threshold is set to threshold + EPSILON here.

Everything else about the notion of *more* or *less* invalid as quoted by Arsapol still holds.

Let me know if the problem is resolved for you.
