### ISSUE TITLE
Finding the life time of a tracker? 

### ISSUE THREAD

**Issue by prnvjb** [nwojke/deep_sort#137]
How to find the life time of a tracker?
I'm making tracker sets to collect objects in every frame? In order to end the collection of each tracker I'm trying to find end of tracker or tracker lifetime.
Thanks for the help!!

**Comment by nwojke** [comment]
I am not sure if I got you correctly. Is [deep_sort.track.Track.age]https://github.com/nwojke/deep_sort/blob/master/deep_sort/track.py#L54) what you are looking for?

**Comment by prnvjb** [comment]
Thanks!!
I created another list with:
deleted_tracks = [t for t in self.tracks if t.is_deleted()]

**Comment by nwojke** [comment]
Ah, ok - makes sense. Looks like you found what you have been looking for. I am closing this issue.
