### ISSUE TITLE
Can this pre-trained model detect hands?

### ISSUE THREAD

**Issue by momo1986** [nwojke/deep_sort#140]
I need to track peoples's hands.
Thanks a lot for contributions.
My question is:
1. How can this be launched? Need I draw anchor box like Open-CV for tracking?
2. Can this model be trained to detect and track hands?
3. If question 2 is not, is this means that the problem becomes a static detection problem?

Thanks & Regards!

**Comment by nwojke** [comment]
Unfortunately, the trained model cannot track hands. I am closing the issue as it seems the code is not well suited for your problem. Please re-open if you have a specific question about the code base.
