### ISSUE TITLE
MOT17

### ISSUE THREAD

**Issue by ccssmania** [nwojke/deep_sort#145]
Hello,

I'm teaming up in a research project, as part of my master degree thesis, and I wonder if it is possible run your project on MOT challenge 17 datase, in order to include your model in our studies. Or at least if you could give us some advice on how to build them up, we'll sincerely thank you.

I hope I could include your model in my project.

Your faithfully,

**Comment by nwojke** [comment]
I haven't touched the MOT17 data yet, personally. If benchmark authors didn't make changes to the data format, you should be able to run the code on MOT17 quite easily. Let me know if you run into specific problems.

**Comment by 15926273249** [comment]
> Hello,
> 
> I'm teaming up in a research project, as part of my master degree thesis, and I wonder if it is possible run your project on MOT challenge 17 datase, in order to include your model in our studies. Or at least if you could give us some advice on how to build them up, we'll sincerely thank you.
> 
> I hope I could include your model in my project.
> 
> Your faithfully,

Have you finished you project on MOT17, is there any change compared to MOT16 ?

**Comment by ccssmania** [comment]
> > Hello,
> > I'm teaming up in a research project, as part of my master degree thesis, and I wonder if it is possible run your project on MOT challenge 17 datase, in order to include your model in our studies. Or at least if you could give us some advice on how to build them up, we'll sincerely thank you.
> > I hope I could include your model in my project.
> > Your faithfully,
> 
> Have you finished you project on MOT17, is there any change compared to MOT16 ?

There was not any  change from MOT16 and MOT17 then  is very easy to run the code.
