### ISSUE TITLE
training on single camera images

### ISSUE THREAD

**Issue by ankitf** [nwojke/deep_sort#148]
Hello, I have images from a single camera. Does it matter if I train the cosine metric model on single camera images only? What repercussions shall I presume if I do this?

**Comment by nwojke** [comment]
I don't see a general issue with using a single camera. Just make sure that your dataset carries *enough* variability in data (lighting conditions etc).

**Comment by ankitf** [comment]
Thanks, Nikolai. Great work, by the way.
