### ISSUE TITLE
Code for training CNN model

### ISSUE THREAD

**Issue by nfoong** [nwojke/deep_sort#15]
Hi Nicolai,

I am working on an MOT project for tracking several different object classes (cars, pedestrians, cyclists, etc.). I understand that the model provided in your github repository for Deep SORT is trained on the MARS dataset which is specific for person re-identification, and was wondering if you could provide the code for training your CNN architecture so that I can train it on my own dataset.

Alternatively, it would be good if you could share some pre-trained models for object classes other than pedestrians.

Thanks for your work on Deep SORT. Cheers!

**Comment by nwojke** [comment]
Code for re-training the network is still not ready for publication (it's a matter of time - or the lack of it), but I have written down a few points in [issue 7](https://github.com/nwojke/deep_sort/issues/7).

Models for classes other than pedestrians would be a nice addition, so feel free to share them once you get results.

**Comment by SophieZhou** [comment]
@nwojke could you explore the model in Caffe framework? I want to use the model in Caffe and I will share the result after that.

**Comment by jinfagang** [comment]
Have the author ready for announce the training code?

**Comment by nwojke** [comment]
See https://github.com/nwojke/cosine_metric_learning

**Comment by Abdelsater** [comment]
Hello Guys, 
Anyone was able to train deep_sort model on his own dataset? modifying my dataset to fit the code is almost impossible, I have more than 12000 images of specific road signs and lights, the problem that all these images are coming from a single camera. the camera id is always 1. how can I customize it to be able to train deep sort on it.

thanks in advance for your help

**Comment by lsmh886** [comment]
> Hello Guys,
> Anyone was able to train deep_sort model on his own dataset? modifying my dataset to fit the code is almost impossible, I have more than 12000 images of specific road signs and lights, the problem that all these images are coming from a single camera. the camera id is always 1. how can I customize it to be able to train deep sort on it.
> 
> thanks in advance for your help

Have you got the train code of deep sort? I am still looking for it, also have the same problem, since I intend to use MOT dataset to train the model instead of MARS or market. Maybe we could help each other I think

**Comment by Abdelsater** [comment]
> > Hello Guys,
> > Anyone was able to train deep_sort model on his own dataset? modifying my dataset to fit the code is almost impossible, I have more than 12000 images of specific road signs and lights, the problem that all these images are coming from a single camera. the camera id is always 1. how can I customize it to be able to train deep sort on it.
> > thanks in advance for your help
> 
> Have you got the train code of deep sort? I am still looking for it, also have the same problem, since I intend to use MOT dataset to train the model instead of MARS or market. Maybe we could help each other I think

yes , why not share with me your email and I will send you my progress

**Comment by lsmh886** [comment]
> > > Hello Guys,
> > > Anyone was able to train deep_sort model on his own dataset? modifying my dataset to fit the code is almost impossible, I have more than 12000 images of specific road signs and lights, the problem that all these images are coming from a single camera. the camera id is always 1. how can I customize it to be able to train deep sort on it.
> > > thanks in advance for your help
> > 
> > 
> > Have you got the train code of deep sort? I am still looking for it, also have the same problem, since I intend to use MOT dataset to train the model instead of MARS or market. Maybe we could help each other I think
> 
> yes , why not share with me your email and I will send you my progress

LJXLSMH886 at gmail.com 
 thanks in advance!

**Comment by mazatov** [comment]
Have you guys been able to train the network on your own dataset?

**Comment by mazatov** [comment]
@lsmh886 , @Abdelsater have you guys been able to train the network on your own dataset?
