### ISSUE TITLE
regarding innovation_cov in kalman_filter.py

### ISSUE THREAD

**Issue by madhu-korada** [nwojke/deep_sort#158]
how can a 4x4 matrix(innovation_cov) and 8x8 matrix(covarience) be added in kalman_filter.py project method?

**Comment by nwojke** [comment]
[This line](https://github.com/nwojke/deep_sort/blob/master/deep_sort/kalman_filter.py#L150) reduces the 8x8 state covariance to a 4x4 measurement covariance. Hope this helps.
