### ISSUE TITLE
Did the project use the Mahalanobis distance?

### ISSUE THREAD

**Issue by seanM29** [nwojke/deep_sort#16]
Hi, Thanks for you work!
the paper(SIMPLE ONLINE AND REALTIME TRACKING WITH A DEEP ASSOCIATION METRIC) mentioned a method that use Mahalanobis distance to get the motion information, however, I only saw the IOU method, so did the project use Mahalanobis distance method? if  used,  which file include it?
Thanks a lot

**Comment by nwojke** [comment]
* [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort/linear_assignment.py#L144)
* [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort/kalman_filter.py#L188)

**Comment by seanM29** [comment]
Thanks a lot
