### ISSUE TITLE
unable to store the resulting video of tracker with the generate_videos.py file

### ISSUE THREAD

**Issue by anzy0621** [nwojke/deep_sort#163]
Hello,
          can someone tell me what command-line arguments I should give for the result_dir and the output_dir.
This the what I'm trying to run : python generate_videos.py  --mot_dir=./vehicles/test                         --result_dir=./output/hypotheses.txt  --output_dir=./videos

But I keep running into errors saying file doesn't exist.
![2](https://user-images.githubusercontent.com/37059022/61585084-91ce5600-ab21-11e9-801d-bc0fe14cd380.JPG)

**Comment by anzy0621** [comment]
Fixed it

**Comment by kaikaizhu** [comment]
Can you tell me how to fix it?
Thank you very much!

**Comment by a243845305** [comment]
Can you tell me how to generate a result video via generate_videos.py?
Thank you very much!

**Comment by qiqingwang577** [comment]
just create a folder named output and create a .txt file named hypotheses.
