### ISSUE TITLE
hit_streak is not used 

### ISSUE THREAD

**Issue by Tengke-Xiong** [nwojke/deep_sort#19]
seems that hit_streak variable in track.py is a dummy variable, is not used at all.

**Comment by nwojke** [comment]
You are right, looks like an artefact. Thanks. If you open a PR to remove it I will merge the changes. Otherwise, I'll take care of it when I find time again.

**Comment by nwojke** [comment]
The dummy variable has been removed in (9410b93)[https://github.com/nwojke/deep_sort/commit/9410b931dae391c44c28d599e7d2e36eb1197d58].
