### ISSUE TITLE
Issues after training VeRI dataset

### ISSUE THREAD

**Issue by hghimanshu** [nwojke/deep_sort#192]
Hey @nwojke, I have trained the model on VeRI dataset for about 122k iterations. The (classification accuracy) value shown on the tensorboard at that time was about 0.98 so I stopped the training. Then I export the model to a **.pb** file. I am facing some issues regarding the deep sort implementation for vehicle tracking.

I am having a initial detection file (.txt file) which I get from my vehicle detector
Below are some of my issues :- 

- do I need to generate a **.npy** file for every video on which I am running my code?
- also, the **.npy** file mostly starts generating detection after the first 3 frames, how can I resolve this issue ?

**Comment by a0981456759** [comment]
hello, Could you share your model, thx

**Comment by hghimanshu** [comment]
well, this issue is solved.

**Comment by phungthengoc** [comment]
please, how to train cosine metric learning for VeriDataset
