### ISSUE TITLE
issue with deep_sort_app.py

### ISSUE THREAD

**Issue by Maxwell2016LeChouchou** [nwojke/deep_sort#193]
Hello, your command about python deep_sort_app.py \
    --sequence_dir=./MOT16/test/MOT16-06 \
    --detection_file=./resources/detections/MOT16_POI_test/MOT16-06.npy \
    --min_confidence=0.3 \
    --nn_budget=100 \
    --display=True
which means you are trying to give the sequence_dir about the test folder of MOT16, however, in your deep_sort_app.py, your function of gather_sequence_info is trying to read the MOT16/test/MOT16-06. However, the MOT16/test/MOT16-06 does not exist gt/gt.txt file, how is that possible to read? The gt/gt.txt only exist in the MOT16/train/  file

**Comment by Amokstakov** [comment]
Were you able to solve this? Running into the same issue when trying to run this

**Comment by Maxwell2016LeChouchou** [comment]
Yes, I run, thats the python code for running the video sequence.
