### ISSUE TITLE
unmatched_tracks in tracker.py

### ISSUE THREAD

**Issue by Tengke-Xiong** [nwojke/deep_sort#20]
in tracker.py line 127
unmatched_tracks = list(set(unmatched_tracks_a + unmatched_tracks_b))

how about the situation that the track included in both unmatched_tracks_a and iou_track_candidates, but excluded  in unmatched_tracks_b? as this track should be matched.

**Comment by nwojke** [comment]
Are you refering to what has been opened in [PR 17](https://github.com/nwojke/deep_sort/pull/17)?

**Comment by Tengke-Xiong** [comment]
Thank you nwojke, same issue in PR 17.
