### ISSUE TITLE
The shape of extracted featuremap is not specific.

### ISSUE THREAD

**Issue by jinfagang** [nwojke/deep_sort#21]
Hi,  thanks for the wonderful work. I have only one question, I print out the detections.npy file, the shape
of MOT16_POI_train/0004 is     ( 40709, 138),  138 is the last dim of featuremap with no doubt.
But 40709 don't make sense, because MOT16_POI_train/0004 has 1050 images.
if every image has a single 1-d featuremap which should be (1050, 138),  **So basically, what is the shape of extracted feature map?**

**Comment by nwojke** [comment]
Hi jinfagang,

sequence 4 has 1050 images. The file MOT16_POI_train/00004.npy contains one row for each detection, so there are in total 40709 detections (multiple for each frame). You can match the detections to the frame index using the first entry in each row.

The appearance descriptor has length 128. The first 10 columns in the detection file contain the MOTChallenge detection, the last 128 the feature descriptor.

**Comment by jinfagang** [comment]
Thanks for detail clarify, I understood now.
