### ISSUE TITLE
Why default --nms_max_overlap=1? 

### ISSUE THREAD

**Issue by Jumabek** [nwojke/deep_sort#22]
Thanks for the amazing work and open source!
Could you help me with the following questions please:

1. Why default --nms_max_overlap=1?  It means no suppression will be performed right?
2. Was it experimentally best threshold for MOT16?

Thanks.

**Comment by nwojke** [comment]
Yes, setting the value to 1 disables non-maxima suppression. If I remember it did not have a large impact on performance for the detections we used (NMS may have been applied before they have been published), but you may experiment with it. It is there to be used when needed.

**Comment by nwojke** [comment]
I am closing this since the question seems resolved.
