### ISSUE TITLE
np.linalg.norm() for normalizing the features

### ISSUE THREAD

**Issue by pandey-anurag** [nwojke/deep_sort#233]
Hello, 
I am trying to understand the use of
```
if not data_is_normalized:
        a = np.asarray(a) / np.linalg.norm(a, axis=1, keepdims=True)
        b = np.asarray(b) / np.linalg.norm(b, axis=1, keepdims=True)
``` 

[here](https://github.com/nwojke/deep_sort/blob/280b8bdb255f223813ff4a8679f3e1321b08cdfc/deep_sort/nn_matching.py#L51)

I tried using the same approach, but I do not get normalized vectors.

```
feat = np.random.rand(3,4)
print(feat)
norm = feat/np.linalg.norm(feat, axis=1, keepdims=True)
print(norm)
print(np.sum(norm, axis=1))
```

Output:
```
[[0.75011799 0.54083259 0.65699116 0.9437311 ]
 [0.1359358  0.80203965 0.87496547 0.74936549]
 [0.43723459 0.27744972 0.64938242 0.42874583]]

[[0.50834226 0.36651309 0.44523179 0.63955059]
 [0.09638997 0.56871384 0.62042441 0.53136342]
 [0.46777829 0.29683141 0.69474604 0.45869654]]

[1.95963773 1.81689164 1.91805229]
```

Please advice.

**Comment by dranaivo** [comment]
@pandey-anurag 

Doing `np.sum(norm, axis=1)` doesn't give the norm of  each of `norm`'s row. Do instead `np.linalg.norm(norm, axis=1, keepdims=True)`.

Output:
```Python
[[1.]
 [1.]
 [1.]]
``` 
Each row vector are normalized.

**Comment by pandey-anurag** [comment]
@dranaivo I understand, I performed L1 norm instead of L2 right?
