### ISSUE TITLE
Has an expected time for releasing training code

### ISSUE THREAD

**Issue by 1474123989** [nwojke/deep_sort#25]
I am wondering how to train with different object other than pedestrains. Is there an issue time for training code? Thanks in advance.

**Comment by nwojke** [comment]
We are working on it at the moment. It might be ready at the end of January.

**Comment by FakhrEldeen** [comment]
@nwojke i am wondering has the training code been published or not ? thanks in advance

**Comment by abewley** [comment]
@nwojke has released training code [here](https://github.com/nwojke/cosine_metric_learning)
