### ISSUE TITLE
Using deep_sort on my own dataset

### ISSUE THREAD

**Issue by aktaseren** [nwojke/deep_sort#277]
Hi @iory @abewley @linuxandchill @kinnzo @nwojke, thanks a lot for making this code available. Can I ask how I can use this code on my own sample video rather than using MOT16 benchmark datasets?

**Comment by danielcrane** [comment]
@aktaseren Do you have the bounding boxes and accompanying feature vectors for each frame in the video you're interested in?

**Comment by aktaseren** [comment]
@danielcrane yes, I have the info of bounding boxes of the objects I am interested to track per frame in my video. However, in terms of feature vectors, I am not sure. I will check this out. Then, I will let you know here.

As for another question, can I implement a different detection algorithm prior to SORT?

**Comment by danielcrane** [comment]
> @danielcrane yes, I have the info of bounding boxes of the objects I am interested to track per frame in my video. However, in terms of feature vectors, I am not sure. I will check this out. Then, I will let you know here.

If you have no feature vectors, or a network/encoder capable of creating them, then you won't really be able to make use of Deep SORT.

The key difference between SORT and Deep SORT is that it includes the use of feature vectors to improve the identification of objects from frame to frame, where SORT just uses Kalman filter predictions + IoU.

With that in mind, if you only have bounding boxes, I'd advise using regular SORT instead.
 
> As for another question, can I implement a different detection algorithm prior to SORT?

As long as it outputs bounding boxes, you should be able to use any kind of detection algorithm that you want!

**Comment by aktaseren** [comment]
Thank you very much @danielcrane. That all makes sense for me now.

**Comment by danielcrane** [comment]
No problem at all, @aktaseren . With regards to using your own detector, just make sure that the bounding boxes are converted to the format SORT/Deep SORT expect to ensure it works smoothly. :)
