### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by pribadihcr** [nwojke/deep_sort#29]
Hi @nwojke,

What is the code's license ?
Thanks

**Comment by nwojke** [comment]
Hi pribadihcr,

the code is licensed under GPL v3.0. GitHub gives a nice overview of this license [here](https://github.com/nwojke/deep_sort/blob/master/LICENSE). Does this work for you?

**Comment by pribadihcr** [comment]
@nwojke,

In a case like people running or walking without change the direction, it is work good. but in a case that contain high occlusion and pose change, it work poor. Does it relate with Re-ID algorithm or tracking issue ?

Thanks

**Comment by pribadihcr** [comment]
Hi @nwojke,

Yes, thank you.
