### ISSUE TITLE
Use for objects other than pedestrian

### ISSUE THREAD

**Issue by pouryajafarzadeh** [nwojke/deep_sort#299]
Can we use the method for other objects such as cars, bikes?

**Comment by Dipankar1997161** [comment]
yes you can use it for any object. The class file needs to be updated accordingly.

**Comment by SalmaZakaria** [comment]
@Dipankar1997161 How to update the class and how can I get it?

**Comment by Dipankar1997161** [comment]
> @Dipankar1997161 How to update the class and how can I get it?

The class file will most probably be there in the Architecture you using. For example if you plan to Yolo with Deep sort, 
Change the class file in Yolo. There is a file or a program where the classes are defined.

**Comment by Dipankar1997161** [comment]
> Ok, I am using deep sort with yolo an I want to return the class predicted from track objects ? is that available? For example: ` tracked_objects = mot_tracker.update_tracks(detections.cpu(), frame)` tracked_objects contains the track id and bbox, how to make it contain the class too?

tools/generate_detections.py

Check the Image Encoder Class in this file. It's here only. 
Over there is a file for custom detections. Hope that helps
