### ISSUE TITLE
can this be realtime?

### ISSUE THREAD

**Issue by harshmunshi** [nwojke/deep_sort#3]
From what I see and read, I have to train the model etc. Would this method work on realtime videos?

For example I analyze the frame detect the BBs and pass it on directly to the feature network. Can it work like that?

**Comment by nwojke** [comment]
The neural network training is done offline, before the actual tracking application. We also provide a pre-trained model. The tracking itself can be realtime if you have a decent GPU.

**Comment by harshmunshi** [comment]
My exact question is, in the sample code you have a directory of images in a specific pattern (the mot format), can the flow be like this:

video input -> detection using faster-RCNN(say for example) -> input to the neural network -> feature computation -> Tracking ? 

You are currently saving it as an npy for each frame, can it be done without saving it, like on the go?

**Comment by nwojke** [comment]
With a few adaptions to the code, this can be done. I have posted some pseudo code in [Issue 4](https://github.com/nwojke/deep_sort/issues/4). Have a look at that code snippet and lete me know if you need more specifics.
