### ISSUE TITLE
What should I do if I want to transplant this project from Python to C++?

### ISSUE THREAD

**Issue by RoseOnCollar** [nwojke/deep_sort#30]
As the title. I want to transplant the project to C++. What is the probability?

**Comment by RoseOnCollar** [comment]
Is there anyone help me?

**Comment by nwojke** [comment]
Hi RoseOnCellar, I am not sure how to help with this question. Sure you can re-implement the algorithm in C++, but this would be an entirely new (software) project.

**Comment by oylz** [comment]
I have impelement it by c++,you can have a look it:https://github.com/oylz/DS
