### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 307509256** [nwojke/deep_sort#31]
OSError: [Errno 2] No such file or directory: './MOT16/test/MOT16-06/img1'

**Comment by hurkal** [comment]
Have you downloaded MOT16 data? Check: https://motchallenge.net/data/MOT16/#download

**Comment by nwojke** [comment]
Closing this one due to inactivity.

**Comment by tonmoyborah** [comment]
Do we have to download 'all data' of 1.9GB?

**Comment by zhujinchao123** [comment]
I have the same problem , 
what we need ?in  sequence_dir=./MOT16/test/MOT16-06
hello,there are **'seqinfo.ini' , 'det (this is a fold)' , 'MOT16-06.mp4'** in sequence_dir=./MOT16/test/MOT16-06
but,I can,t run the demo ,idont kown where worse?
