### ISSUE TITLE
Testing with my data

### ISSUE THREAD

**Issue by hurkal** [nwojke/deep_sort#32]
Hello. I want to track people using on my dataset, but I have a problem about adapting it to the project. In this case, do I have to provide .det file?

**Comment by leonardean** [comment]
you need:
1) provide det file which contains the detection rectangles of each frame
2) images of the video sequence

**Comment by hurkal** [comment]
When I run generate_detections.py file, it warns me that I have to provide a non-empty file. How can I generate this .det file? I mean, I also want the detections.

**Comment by nwojke** [comment]
We don't provide a pedestrian detector ourselves. Others here have tried YOLO and tf-faster-rcnn. Have a look at the closed issues.
