### ISSUE TITLE
Tracking for Street LIghts

### ISSUE THREAD

**Issue by shuchitagupta** [nwojke/deep_sort#33]
Hi,

I wanted to ask that how can I use deepSort to track street lights. What model do I need to change? And can I retrain this model to use for detection of street lights?

Your help would be really appreciated. Thanks

**Comment by nwojke** [comment]
If you continue to track in image coordinates you could probably re-use most of the code (you might have to adapt the Kalman filter parameters, though). However, the CNN is trained on pedestrians so you will have to re-train.

**Comment by shuchitagupta** [comment]
Can I get the model that needs to be retrained?

**Comment by nwojke** [comment]
The pre-trained model is linked in the READE ([link](https://owncloud.uni-koblenz.de/owncloud/s/f9JB0Jr7f3zzqs8)).

**Comment by shuchitagupta** [comment]
This model is for pedestrians. Could I get the initial model so I can train it for street lights?

**Comment by nwojke** [comment]
Sorry, I don't have any other model to start fine tuning from as the pedestrian model has been trained from scatch on [MARS](http://www.liangzheng.com.cn/Project/project_mars.html).
