### ISSUE TITLE
Attempted to use a closed Session

### ISSUE THREAD

**Issue by mayidu** [nwojke/deep_sort#34]
Hello，
When I use the deep sort in py-faster-rcnn, there are some errors bescause the py-faster-rcnn is  caffe,the deep sort is tensorflow, so I change the generate detection code, but when use the generate_detections.create_box_encoder to get encoder, I get the error: RuntimeError: Attempted to use a closed Session. I don't know how to solve this problem!
thanks~

**Comment by mayidu** [comment]
This question have been solved! thx

**Comment by frankzhuo** [comment]
how to fix?

**Comment by mayidu** [comment]
Do you get this question also?

**Comment by JpHu2017** [comment]
@mayidu Hi, mayidu. Do you convert it to caffe sucessfully? Could you give some advice?
