### ISSUE TITLE
Can we run generate detections side by side while object detector is running?

### ISSUE THREAD

**Issue by deamonDevs** [nwojke/deep_sort#36]
I want to know is there any way to optimize the time by running generate_detections side by side while we are running object detector to get the B-Boxes... I referred the issue #4 I want the flow like:
1) Detect_objects in frame -> after detecting objects run generate_detections to get encodings for .npy file -> after video gets finished store all the encodings in .npy file ->  run deep_sot_app

**Comment by deamonDevs** [comment]
I am trying to get this done but facing some errors in encoding part...  please help... Thanks in advance...

**Comment by deamonDevs** [comment]
I am done with the problem... Thank you...!!!

**Comment by anshu1106** [comment]
@deamonDevs Can you please share your code to generate detections while object detector is running?

**Comment by nvnnghia** [comment]
@deamonDevs I'm interested. How did you do that and how about performance? Thank you

**Comment by Qidian213** [comment]
I combined deep_sort and yolov3 ,it can tracking real-time use my laptop's camera

https://github.com/Qidian213/deep_sort_yolov3 @nvnnghia @anshu1106

**Comment by ss199302** [comment]
@deamonDevs  What object do you use for object detection, what is the generated file? Thank you！
