### ISSUE TITLE
Usage on RADAR detections

### ISSUE THREAD

**Issue by ashnarayan13** [nwojke/deep_sort#37]
Hi,

I wanted to know if the deep sort can be used to track objects from RADAR data. I have used the sort for images and it works great. But will it work for RADAR+Camera fusion or just radar detections? 

Thanks!

**Comment by nwojke** [comment]
In the end its a Kalman filtering based approach with appearance association cost. You could change the Kalman filter system representation to your RADAR application. This would mostly be a conventional single hypothesis tracker with global nearest neighbor data assocation, but rely on appearance cost for the assocation, in case you still want to use that part of the project (which I would say is the relevant contribution).
