### ISSUE TITLE
Train car model

### ISSUE THREAD

**Issue by mayidu** [nwojke/deep_sort#38]
Hello, I train car model with triplets Re-id, and I got for files that .data, .index, .meta. The deep sort use a .ckpt file for model, but I train model no have this file, so how can I do? Do you give me some suggest?than you!

**Comment by nwojke** [comment]
If you have `model.ckpt-iteration.data`, `model.ckpt-iteration.index`, `model.ckpt-iteration.meta` then you can pass in `model.ckpt-iteration` as filename to the deep_sort_app. This should work fine.

**Comment by mayidu** [comment]
Hello, nwojke,
I trained model by using triplets Re-id, and used model in deep sort, it works well! I will use other dataset to train some other models for tracking other things. Thanks your work!

**Comment by nwojke** [comment]
I am glad to hear you got it to work.

**Comment by pranamesh** [comment]
Hello @mayidu 
Can you please share which dataset you used for training car model? Also, is it possible to share your training code since the original code for training CNN model is still under preparation by @nwojke

**Comment by mayidu** [comment]
Surely! I use the triplets re-id model to train, you can find it in github! The dataset you need to apply and I can't to give you. Also, you can use free dataset which address is https://medusa.fit.vutbr.cz/traffic/datasets/  you can try!

**Comment by Silencesss** [comment]
@mayidu  could you share the training code ?

**Comment by mayidu** [comment]
OK! https://github.com/VisualComputingInstitute/triplet-reid
you can try!
@Silencesss

**Comment by Silencesss** [comment]
could you share your trained model on car ? i did not train it successfully.I really need it .thank you @mayidu

**Comment by qiyayun** [comment]
do you use  the checkpoint to generate a .pb file with freeze.py?   if I use resnet_v1_50 as the CNN architecture in triplets Re-id, need I  to change the cnn architecture to resnet_v1_50 in freeze.py? @mayidu

**Comment by mayidu** [comment]
hello! Thank you very much for your question and very happy to answer you！I don't use freeze.py!~
There were not freeze.py! I only used train.py to train model! If you want to use resnet_v1_50 to trian model, you can modify the param in train.py which --model_name!
I hope I can help you, thank you.





At 2018-11-07 20:57:45, "qiyayun" <notifications@github.com> wrote:


do you use the checkpoint to generate a .pb file with freeze.py? if I use resnet_v1_50 as the CNN architecture in triplets Re-id, need I to change the cnn architecture to resnet_v1_50 in freeze.py? @mayidu

**Comment by mayidu** [comment]
I modified deep sort code to use the model file from triplets. You can try!



At 2018-11-08 10:27:44, "qiyayun" <notifications@github.com> wrote:


thank you for your reply,how do you use the car model trained from triplets Re-id to deep-sort file, the deep-sort file only use .pb file to generate features. Are them compatiable?

**Comment by qiyayun** [comment]
哈哈谢谢你的回复，其实我已经用triplet训练好一个模型了，所以我想问问，你是怎么把训练好的模型用到deepsort中的，我貌似不能直接用ckpt的文件代替deepsort里面的.pb文件

**Comment by qiyayun** [comment]
哈哈谢谢你的回复，其实我已经用triplet训练好一个模型了，所以我想问问，你是怎么把训练好的模型用到deepsort中的，我貌似不能直接用ckpt的文件代替deepsort里面的.pb文件

**Comment by qiyayun** [comment]
@mayidu期待你的回复哈哈

**Comment by qiyayun** [comment]
@mayidu期待你的回复哈哈

**Comment by mayidu** [comment]
在deep sort中修改一下代码，两个代码用的restore的方式不一样，我以前是参考SSD-Tensorflow的代码改的，你可以看一下，把代码修改一下就可以了。





在 2018-11-08 14:15:47，"qiyayun" <notifications@github.com> 写道：


哈哈谢谢你的回复，其实我已经用triplet训练好一个模型了，所以我想问问，你是怎么把训练好的模型用到deepsort中的，我貌似不能直接用ckpt的文件代替deepsort里面的.pb文件

**Comment by songjunqianli** [comment]
@mayidu 同学你好，你是怎么训练它进行车辆的跟踪的啊？

**Comment by ss199302** [comment]
@mayidu  Hello, which code do you use for training? Are you referring to the code https://github.com/Visual Computing Institute/triplet-reid or cosine_metric?

**Comment by ss199302** [comment]
@mayidu  你好。请问你使用https://github.com/VisualComputingInstitute/triplet-reid训练的权重模型只需要修改代码读取ckpt文件就可以直接用在deepsort中吗？

**Comment by ss199302** [comment]
@mayidu 你好，我使用 https://github.com/VisualComputingInstitute/triplet-reid官方训练好的权重模型生成了pb文件，但是把它用在deepsort中时，也会报错，你能告诉我怎么回事吗？万分感谢

**Comment by mayidu** [comment]
你需要修改一下deepsort里面模型恢复的文件



在 2019-01-19 10:50:42，"ss199302" <notifications@github.com> 写道：


@mayidu 你好，我使用 https://github.com/VisualComputingInstitute/triplet-reid官方训练好的权重模型生成了pb文件，但是把它用在deepsort中时，也会报错，你能告诉我怎么回事吗？万分感谢

**Comment by ss199302** [comment]
@mayidu 谢谢你的回复，我也尝试过修改deepsort模型回复的文件，但我能力有限，没能正确恢复模型文件。我是一名毕业生，使用deepsort用来做毕业论文，看了你对于别人的回复，我也想替换掉权重模型为了使跟踪效果更好。我把deepsort用于毕业论文，而且毕业论文里不会贴代码，我也不会用于其他任何事情，希望你能告诉我如何恢复模型文件。我将非常非常感激！我的邮箱是1226005872@qq.com。期待收到你的回复。

**Comment by ss199302** [comment]
@mayidu  你好，你使用https://github.com/Visual Computing Institute 的权重模型结合deepsort效果测试过吗，MAP值是多少呢？谢谢！
