### ISSUE TITLE
Run Deep Sort with a videofile

### ISSUE THREAD

**Issue by Ravisik** [nwojke/deep_sort#4]
Hi ! 

Do you know if there is a simple way to run Deep Sort using detection file + video file using open cv instead of using a folder of images? 

Thanks!

**Comment by Ravisik** [comment]
Thanks for your response.
I manage to use my own code adapted for video : 

```
def generate_detections_video(encoder, video, name_out, detection):

    """Generate detections with features. Modification with video
    """

    detections_in = detection
    detections_out = []

    frame_indices = detections_in[:, 0].astype(np.int)
    min_frame_idx = frame_indices.astype(np.int).min()
    max_frame_idx = frame_indices.astype(np.int).max()

    camera = cv2.VideoCapture(video)

    for frame_idx in range(min_frame_idx, max_frame_idx + 1):
        print("Frame %05d/%05d" % (frame_idx, max_frame_idx))
        mask = frame_indices == frame_idx
        rows = detections_in[mask]

        if frame_idx not in frame_indices:
            print("WARNING could not find image for frame %d" % frame_idx)
            continue
        camera.set(cv2.CAP_PROP_POS_FRAMES, frame_idx-1);
        (grabbed, bgr_image) = camera.read()
        # bgr_image = cv2.imread(image_filenames[frame_idx], cv2.IMREAD_COLOR)
        rows[:, 4:6] -= rows[:, 2:4]  # convert to [x1,y1,x2,y2] to [x1,y1,w,h]
        features = encoder(bgr_image, rows[:, 2:6].copy())
        detections_out += [np.r_[(row, feature)] for row, feature
                           in zip(rows, features)]

    # output_filename = os.path.join(output_dir, "%s.npy" % sequence)
    np.save(name_out, np.asarray(detections_out), allow_pickle=False)
```

For the tracking: 

`    camera = cv2.VideoCapture(video)
    frame_idx =0;
    min_frame_idx = int(detections_file[:, 0].min())
    max_frame_idx = int(detections_file[:, 0].max())
    min_confidence = 0.95
    min_detection_height = 0
    nms_max_overlap = 0.3
    if (display):
        plt.ion()
        fig = plt.figure()

    while True:
        (grabbed, frame) = camera.read()
        frame_idx += 1;
        print("Processing frame %05d" % frame_idx)

        # Load image and generate detections.
        detections = create_detections(detections_file, frame_idx-1, min_detection_height)
        detections = [d for d in detections if d.confidence >= min_confidence]

        # Run non-maxima suppression.
        boxes = np.array([d.tlwh for d in detections])
        scores = np.array([d.confidence for d in detections])
        indices = preprocessing.non_max_suppression(boxes, nms_max_overlap, scores)
        detections = [detections[i] for i in indices]

        # Update tracker.
        tracker.predict()
        tracker.update(detections)

        # Update visualization.
        if display:
            ax1 = fig.add_subplot(111, aspect='equal')
            # fn = 'mot_benchmark/%s/%s/img1/%06d.jpg'%(phase,seq,frame)
            ax1.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            plt.title(' Tracked Targets')

        # Store results.
        for track in tracker.tracks:
            if not track.is_confirmed() or track.time_since_update > 1:
                continue
            bbox = track.to_tlwh()
            results.append([
                frame_idx, track.track_id, bbox[0], bbox[1], bbox[2], bbox[3]])

            A = np.in1d (track.track_id, id_detected,  invert=True)
            if A == True:
                id_detected = (np.append(id_detected,int(track.track_id)))
                time_detected = np.append(time_detected,frame_idx/33.)

            if (display):
                ax1.add_patch(patches.Rectangle((bbox[0], bbox[1]), bbox[2], bbox[3], fill=False, lw=3,ec=colours[track.track_id % 32, :]))
                ax1.set_adjustable('box-forced')
                plt.text(bbox[0], bbox[1], str(track.track_id))

        if(display):
          fig.canvas.flush_events()
          plt.draw()
          ax1.cla()

        if grabbed == False:
            break
`

**Comment by rishabh135** [comment]
@Ravisik  Can you please explain how will I use your function generate_detections_video for my test_video (test.mp4) , what does the argument detections specify (are they the bboxes of the objects in the video ,if so can I use YOLO to get them ) ?

**Comment by Ravisik** [comment]
Hi!

generate_detections_video(encoder, video, name_out, detection) is approximately the same as the original generate_detections.

video is the path to test.mp4
detection is a txt with bboxe object in the MOT format (as explained in the readme of this project). I used Py-faster-rcnn to get detections, but any detector should be working.

**Comment by bendidi** [comment]
Hello, @Ravisik 
I'm very interested in your work with how you merged a detection neural network with deep_sort !
Is it possible for you to share your implementation to get an idea on how it's done !

Thank you !

**Comment by bendidi** [comment]
Hello, 
what I don't understand is the generation of features for each detection , and is it necessary to keep it in a numpy format ?maybe just keep the features in a variable for the duration of the video ?

**Comment by Ravisik** [comment]
The generation of features for each detection is made by the deep sort neural network (128 features for each detection regarding the Region Of Interest). 

No, you can generate detection and features frame by frame, you don't have to stock it:
frame --> ROI provided by py-faster-rcnn --> feature detection by deep sort --> tracking

**Comment by bhavikajalli** [comment]
@Ravisik Could you tell me how can I do the feature detection ? I have followed the above instructions `encoder = generate_detections.create_box_encoder(
        PATH_TO_TENSORFLOW_CHECKPOINT_FILE)` and given the address to the model I had trained with Yolo. However the code is unable to read my variables.
Should I have given a different checkpoint address ?
Thanks for the help.

**Comment by bendidi** [comment]
PATH to checkpoint file is the path to the deep sort checkpoint file, not yolo
you can't load yolo weights in deep sort network

**Comment by bhavikajalli** [comment]
Thank you or helping me out !

**Comment by bhavikajalli** [comment]
Thank you or helping me out !

**Comment by Zumbalamambo** [comment]
@Ravisik can you please share with us the code so it will let me learn it. Im having difficulty in running it on video files.

**Comment by bendidi** [comment]
@Zumbalamambo , I've put in [here](https://github.com/nwojke/deep_sort/issues/13) my try to run it with a video file and using YOLO for detection's , although I didn't get good results, it might give you some insights on how to do it

**Comment by Ravisik** [comment]
Sorry to respond a bit late.
@bhavikajalli I didn't use YOLO for the feature detection, only the net trained by @nwojke . Did you managed to extract features? 

@Zumbalamambo : I don't understant what code do you want, could you be more specific? You can find upster the part used to run with py-faster-rcnn + deep sort (in fact you just have to do some little changes). 

You can obviously use an other detector instead of py-faster-rcnn. However it seems to work really well and I didn't try other detectors. You can use an other detection in "generate_detections_video(encoder, video, name_out, detection)" by remplacing the variable detection by your own detections!

**Comment by Ravisik** [comment]
As I explained before: you have to do detection with py-faster-rcnn and then a tracking using deep sort.

Of course, you can change you detection system or your tracking system, it's up to you!

**Comment by bendidi** [comment]
Hello @Ravisik 
did you run in [this problem](https://github.com/nwojke/deep_sort/issues/13)  when you implemented with py-faster-rcnn , the detection that I get are accurate using YOLO , but the tracking is not confirmed and comes with a width of 0 ?
PS: what fps do you get with py-faster-rcnn ? I'm at 15 fps with YOLO in 8Gb GPU

**Comment by Ravisik** [comment]
Hi! 

I had the same error using py-faster-rcnn : if your detection are in the wrong format (for instance if you use x,y,x2,y2, features instead of x,y,w,h,features) the features generation will not work. Do you have problem with the feature generation?

Using faster-rcnn with a 2G GPU I didn't manage to get a realtime application, I don't know if a faster gpu can sove it

**Comment by haroonchoudery** [comment]
I keep getting the following error when running the following:

`encoder = generate_detections.create_box_encoder("resources/networks/mars-small128.ckpt-68577")`

Error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-93897adff7eb> in <module>()
     10 CHECKPOINT_PATH = os.path.join('resources', 'networks', 'mars-small128.ckpt-68577')
     11 
---> 12 encoder = generate_detections.create_box_encoder(CHECKPOINT_PATH)
     13 video = os.path.join(VIDEO_DIR, VIDEO_FILE)
     14 name_out = 'generated_detections.txt'

~/player-speed/object-detection/app/generate_detections.py in create_box_encoder(model_filename, input_name, output_name, batch_size)
     98 
     99 def create_box_encoder(model_filename, input_name="images",
--> 100                        output_name="features", batch_size=32):
    101     image_encoder = ImageEncoder(model_filename, input_name, output_name)
    102     image_shape = image_encoder.image_shape

~/player-speed/object-detection/app/generate_detections.py in __init__(self, checkpoint_filename, input_name, output_name)
     79             graph_def.ParseFromString(file_handle.read())
     80         tf.import_graph_def(graph_def, name="net")
---> 81         self.input_var = tf.get_default_graph().get_tensor_by_name(
     82             "net/%s:0" % input_name)
     83         self.output_var = tf.get_default_graph().get_tensor_by_name(

//anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in get_tensor_by_name(self, name)
   3497       raise TypeError("Tensor names are strings (or similar), not %s." %
   3498                       type(name).__name__)
-> 3499     return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
   3500 
   3501   def _get_tensor_by_tf_output(self, tf_output):

//anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in as_graph_element(self, obj, allow_tensor, allow_operation)
   3321 
   3322     with self._lock:
-> 3323       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
   3324 
   3325   def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):

//anaconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   3363           raise KeyError("The name %s refers to a Tensor which does not "
   3364                          "exist. The operation, %s, does not exist in the "
-> 3365                          "graph." % (repr(name), repr(op_name)))
   3366         try:
   3367           return op.outputs[out_n]

KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."
```

Any ideas why this might be?

**Comment by haroonchoudery** [comment]
@Ravisik curious — what is your variable `colours` set to in `ec=colours[track.track_id % 32, :])`?

**Comment by francoisDupre** [comment]
Hello @Ravisik,
could you explain where precisely to insert the two snippets of code?
If I understand well, generate_detections_video is meant to replace generate_detections
But, what precisely should the tracking snippet replace? Where should it be inserted?

Thanks !

**Comment by Qidian213** [comment]
Maybe this can help you , I combined deep_sort and yolov3 ,it can tracking real-time use my laptop's camera.

https://github.com/Qidian213/deep_sort_yolov3

**Comment by zhujinchao123** [comment]
> Hi !
> 
> Do you know if there is a simple way to run Deep Sort using detection file + video file using open cv instead of using a folder of images?
> 
> Thanks!

@Ravisik hello 
I have the same problem , 
what we need ?in  sequence_dir=./MOT16/test/MOT16-06
hello,there are **'seqinfo.ini' , 'det (this is a fold)' , 'MOT16-06.mp4'** in sequence_dir=./MOT16/test/MOT16-06
but,I can,t run the demo ,idont kown where worse?

I think your question is same as me?
use mp4 to instead  **a folder of images**
This **sequence_dir=./MOT16/test/MOT16-06** need mp4 or  a folder of images

**Comment by zhujinchao123** [comment]
> Essentially, you'd have to wrap the [frame callback](https://github.com/nwojke/deep_sort/blob/master/deep_sort_app.py#L166) with your own code that reads images from an OpenCV VideoCapture. This should not be hard to do.
> 
> If you need to generate features on the fly, that is also possible with a bit of work. This snippet of pseudo code shows how to call the feature encoder
> 
> ```
> import generate_detections
> from deep_sort.detection import Detection
> 
> def main():
>     # Start up your application, then generate the encoder function.
>     encoder = generate_detections.create_box_encoder(
>         PATH_TO_TENSORFLOW_CHECKPOINT_FILE)
> 
>     # Now, enter the application main loop. Should be something like this:
>     for image, detections in my_data_source:
>         # - image is a BGR color image
>         # - detections is an Nx4 matrix of bounding boxes in
>         #   format (x, y, w, h) where (x, y) is the top-left corner
>         #   and (w, h) is the extent
>         # - features is an Nx128 matrix of corresponding appearance descriptors
>         features = encoder(image, detections)
>         
>         # Generate a list of detections (we simply set the confidence
>         # score to 1.0 here).
>         detections = [
>             Detection(bbox, 1.0, feature) for bbox, feature in
>             zip(detections, features)]
> 
>         # Call the tracker
>         tracker.predict()
>         tracker.update(detections)
> 
>         # Go on and visualize the results, etc.
> ```



> Hi !
> 
> Do you know if there is a simple way to run Deep Sort using detection file + video file using open cv instead of using a folder of images?
> 
> Thanks!

are there a fold of images in  **sequence_dir=./MOT16/test/MOT16-06**  or **.mp4**
if there are a fold of images ,can you tell me  where to get a fold of images ?

**Comment by qiumei1101** [comment]
Hi, can anyone tell me how to extract the features from yolo of each predicted bounding box, other than send the detected bounding box to another cnn to extract features again?

**Comment by qiumei1101** [comment]
> Hello @Ravisik
> did you run in [this problem](https://github.com/nwojke/deep_sort/issues/13) when you implemented with py-faster-rcnn , the detection that I get are accurate using YOLO , but the tracking is not confirmed and comes with a width of 0 ?
> PS: what fps do you get with py-faster-rcnn ? I'm at 15 fps with YOLO in 8Gb GPU

hi can you check my question and discuss about it?
Hi, can anyone tell me how to extract the features from yolo of each predicted bounding box, other than send the detected bounding box to another cnn to extract features again?
