### ISSUE TITLE
Using deep SORT in your own project ?

### ISSUE THREAD

**Issue by Phoebe-star** [nwojke/deep_sort#40]
Using deep SORT in your own project?
how to do it ?
thanks

**Comment by alexanderfrey** [comment]
Hi, did you make it work in your own project mean while ?

**Comment by nwojke** [comment]
You have to wrap the tracker into your own frame-grabbing and data processing loop. Maybe [this issue](https://github.com/nwojke/deep_sort/issues/13) is helpful to you?

**Comment by Clara85** [comment]
@nwojke What is the last number for each detection in `det.txt`? I can't figure this out and this seems not being used, so I just put them to `-1`. But but I keep getting `WARNING: Failed to extract image patch: [ 69. 134. -29. -51.]`, does it have something to do with this faiture? Cause my detections are fine, they are all positive. Thanks a lot!

**Comment by Phoebe-star** [comment]
yes , thanks

**Comment by Qidian213** [comment]
I combined deep_sort and yolov3 ,it can tracking real-time use my laptop's camera

https://github.com/Qidian213/deep_sort_yolov3

**Comment by yeyewen** [comment]
> I combined deep_sort and yolov3 ,it can tracking real-time use my laptop's camera
> https://github.com/Qidian213/deep_sort_yolov3

@Qidian213 Hi I see that,but you mentioned that the 
![image](https://user-images.githubusercontent.com/37136363/62610905-27961d80-b937-11e9-8fd9-921e2a014b03.png)
So what's your laptop configuration?
