### ISSUE TITLE
print   <object at 0x7f87fe29c710>

### ISSUE THREAD

**Issue by Phoebe-star** [nwojke/deep_sort#41]
line 172  ,  detections = [d for d in detections if d.confidence >= min_confidence]      

I want to print  the line 172  detections in  deep_sort_app.py  
but it show  the 
[<deep_sort.deep_sort.detection.Detection object at 0x7f87fe29c710>]

have any method  to print value?

**Comment by nwojke** [comment]
We didn't implement a print function for detections so you have to create your own or print attributes directly.

**Comment by Phoebe-star** [comment]
thanks for your keyword ,  I got it .
