### ISSUE TITLE
min cost matching 

### ISSUE THREAD

**Issue by Phoebe-star** [nwojke/deep_sort#42]
the    ci,j = λ d(1)(i, j) + (1 − λ)d(2)(i, j)   is  in the paper  (5)

where is the code  to do the  (5)?

**Comment by nwojke** [comment]
It's not explicitly in the code since we set it to 0, but the point to add it would be [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort/tracker.py#L99) where we simply gate the cost matrix instead of weighting in the Mahalanobis distance.

**Comment by nwojke** [comment]
Closed due to inactivity. Re-open the issue if you need further clarificatio.

**Comment by ss199302** [comment]
@nwojke  Can you tell me how to add d(1)(i,j) to paper (5)
