### ISSUE TITLE
Is it a mistake in your kalman_filter.py 's code ?

### ISSUE THREAD

**Issue by Warden7** [nwojke/deep_sort#44]
Hi ,

Thanks for your code.
I tried to make a better understand your code with some source of kalman filter.
On the line of 184 of kalman_filter.py:

 **184       new_covariance = covariance - np.linalg.multi_dot((
                        kalman_gain, projected_cov, kalman_gain.T))**

I can't understand it well.Because it seems conflict with my resource of kalman filter.

![image](https://user-images.githubusercontent.com/25070009/35615762-1c04d70a-06ae-11e8-8efb-2cc0f4c4138a.png)

Can you make some explanation ? thx

**Comment by nwojke** [comment]
Sorry for the late respone. There are different versions of the Kalman filter which are equivalent but have different numerical properties (compare, e.g., the German and English version of Wikipedia [here](https://de.wikipedia.org/wiki/Kalman-Filter#Korrektur) and [here](https://en.wikipedia.org/wiki/Kalman_filter#Update); the unscented Kalman filter in [Wikipedia](https://en.wikipedia.org/wiki/Kalman_filter#Unscented_Kalman_filter) also uses the former one used in the ``deep_sort`` code).

**Comment by nwojke** [comment]
I close this for now; re-open if you have open questions.

**Comment by mazatov** [comment]
I just came across the same issue and just wanted to clarify your answer. Which definition of Kalman filter did you use? I can't seem to figure out how you calculate `Kalman gain` and the new estimates for `new_mean` and `new_covariance`. It seems to be not in line with both German and English version of Wikipedia articles on Kalman Filter. 

Was there a specific reason why you chose one estimate over the other?

**Comment by nwojke** [comment]
I'd say don't worry to much about the different Kalman filter implementations. With the implemented models, I don't think you will run into numerical issues with either version. Cholesky is [faster than taking the inverse and numerically stable](https://en.wikipedia.org/wiki/Cholesky_decomposition#Applications).

**Comment by mazatov** [comment]
After doing some math with matrices yesterday, I think the two implementations are actually the same. Some equations simplified once you consider covariance matrix being symmetric. That's cool about Cholesky being faster, very useful tip!

**Comment by ZouJiu1** [comment]
it's helpful
