### ISSUE TITLE
Running on ROS

### ISSUE THREAD

**Issue by ashnarayan13** [nwojke/deep_sort#45]
Hi, 
I want to run the algorithm on ROS. 
I have built the methods that I will need in getting images and their corresponding detections at the same time in the correct format. 
I am not sure where I should change the deep_sort_app.py to take input from detections and image messages from ROS. Any insights? 

Thanks!

**Comment by alexanderfrey** [comment]
Hi, can you elaborate on how you created your own detections ?

**Comment by nwojke** [comment]
The tracker itself is just a sequence of calls to ``predict`` and ``update`` [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort_app.py#L182). So you have to create a node with a callback to the image topic, call the detector, and then convert detections into the [expected format](https://github.com/nwojke/deep_sort/blob/master/deep_sort/detection.py#L5). Maybe  [this issue](https://github.com/nwojke/deep_sort/issues/13) helps?

**Comment by Clara85** [comment]
I think the proper way to use this repo is to package it and use it as a package, but this is not done.You can follow python packaging [guidline](https://packaging.python.org/tutorials/distributing-packages/) by adding `setup.py`, `setup.cfg`, `MANIFEST.in` and `requirements.txt`, then clone the project into your repositiory, and `pip install deep_sort\` maybe you can take a look at the [darkflow](https://github.com/thtrieu/darkflow) project as an example.

**Comment by ashnarayan13** [comment]
@alexanderfrey  I used a neural network to perform the object detection and then used the generate_detections to create the required feature descriptors for the deep SORT. That works for me, but not yet working with ROS as I am still fixing the background stuff required to get it running in ROS

**Comment by ashnarayan13** [comment]
@Clara85 I am doing the same, I am planning on using the deep SORT as a backend and just a node to feed the images as well as detections. My only issue is that computing the feature descriptor doesn't seem to be real-time.

**Comment by Clara85** [comment]
@ashnarayan13 Efficiency is always a problem, maybe you can write your results to some database and then query them from backend. We use google cloud bigquery.

**Comment by nwojke** [comment]
If any of you finds the time to properly package this code, a pull request is always welcome.

**Comment by ilyas95** [comment]
I have created a repository using YOLO and SORT in ROS: if someone is interested:
https://github.com/ilyas95/sort-deepsort-yolov3-ROS

**Comment by lchop** [comment]
Hello all,

I am also interested, any updates ? any repo ? I tried the above package but it is not properly working
