### ISSUE TITLE
'--display=False' doesn't work in argparse

### ISSUE THREAD

**Issue by animebing** [nwojke/deep_sort#49]
When I run `deep_sort_app.py` with `--display=False` or `--display=false`, the tracking result is still displayed, after searching on google, it seems that argument with `bool` type in `argparse` doesn't work, maybe it's better to delete the `type=bool` and add `action='store_true'` for argument `display`.

**Comment by nwojke** [comment]
Thanks for pointing this out.

**Comment by nwojke** [comment]
Has been fixed.
