### ISSUE TITLE
Tracker follow the wrong person

### ISSUE THREAD

**Issue by Ravisik** [nwojke/deep_sort#5]
Hello,

Situation:
Person A is tracked and is about to leave the window of observation
Person B is not tracked yet and will cross the way of Person A (at the observation's border). 

I oberseved that the tracker is often wrong and will say that Person A is Person B (like if Person A is going backward).

Is there a way to avoid this kind of error? I thought to code an algrotihm that avoid that the tracker goes backward but if you have any trick it could be cool!

Thanks in advance ;)

**Comment by Ravisik** [comment]
I managed to solve this issue using the "mean" vector of deep_sort.

--> This vector will increase if the person walk always in the same direction. If the person walk backard, mean will decrease. Detecting this detection with a treshold seems quite efficient to avoid that a same track_id is assigned to 2 different person.

**Comment by virraaj** [comment]
Hi, I am facing the same issue on yolov3. Can you elaborate how did you fix it. How did you use the mean vector?
