### ISSUE TITLE
Could I get the trained label?

### ISSUE THREAD

**Issue by shijieS** [nwojke/deep_sort#53]
Hi, could I get MOT16 labels for detection which can be used for training a detector?

**Comment by animebing** [comment]
@shijieS you can download MOT16 dataset from [https://motchallenge.net/data/MOT16/](https://motchallenge.net/data/MOT16/), you can find the tracking groundtruth and there is bounding box annotation in the groundtruth

**Comment by nwojke** [comment]
@animebing Thanks for helping out.
