### ISSUE TITLE
Usage for euclidean distance

### ISSUE THREAD

**Issue by animebing** [nwojke/deep_sort#54]
There is the metric in the code for using euclidean distance, but it is hard to set threshold for that, because this distance varies greatly compared to cosine distance, is there any reference for setting the euclidean distance threshold? Thanks.

**Comment by nwojke** [comment]
Are you talking about the appearance feature? If the cosine distance is more stable, what is the motivation for using Euclidean distance instead?

**Comment by animebing** [comment]
Yes, I am talking about appearance feature. My motivation for Euclidean distance is that in some person ReID method, the feature is not normalized during training, such as pure VGG16 FC feature, so in this case, maybe Euclidean distance is a better choice, but the threshold is not easy to set.

**Comment by nwojke** [comment]
In [Issue 61](https://github.com/nwojke/deep_sort/issues/61) if gave a rough outline of the way we found the threshold of the cosine similarity. The same procedure could be applied to the Euclidean distance but it will require some coding.

If, in the end, the distance varies too much then this could indicate issues with the discrimination capabiltiies of the feature representation in the tested scenarios.

**Comment by animebing** [comment]
I just notice the issue 61, which will help me a lot, thank you.
