### ISSUE TITLE
Kalman filter gating

### ISSUE THREAD

**Issue by haithamkhedr** [nwojke/deep_sort#56]
I wonder what is the kalman filter gating used in [tracker.py](https://github.com/nwojke/deep_sort/blob/b0ddebfc7a405d1a26d8e73ec0dc20acf77aa99d/deep_sort/tracker.py#L99)?

I have a problem that when a detection is dropped for one frame than appears in the following frame, it is not correctly associated with the old track and a new track is created for the detection. When I commented this function it worked much better

**Comment by nwojke** [comment]
Gating is used to rule out infeasible matches (i.e., the ones with very very low probability). If the gating causes issues in your application, then the Kalman filter motion model is not configured properly for your scenario and you need to increase the uncertainty [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort/kalman_filter.py#L52). This will involve parameter tuning.
