### ISSUE TITLE
Tentative tracks with age > 1 have no chance to match 

### ISSUE THREAD

**Issue by DenerKup** [nwojke/deep_sort#59]
This line for me looks like a bug: https://github.com/nwojke/deep_sort/blob/master/deep_sort/iou_matching.py#L74

**My understanding of algo.**

1. We have two types of active tracks: confirmed (>= n_init detections), tentative ( < n_init detections). 
1. We process confirmed tracks through matching cascade and get matched-confirmed and unmatched-confirmed. [Code link](https://github.com/nwojke/deep_sort/blob/master/deep_sort/tracker.py#L111)
1. Than we take unmatched-confirmed with age == 1 and and tentative for IOU matching. [Code link](https://github.com/nwojke/deep_sort/blob/master/deep_sort/tracker.py#L117)
1. But after that the suspicious line of code from the first link gives no chances to continue for tentative tracks with age > 1.

**Comment by animebing** [comment]
@DenerKup, in the paper, it is said that for the tentative track, it has to be matched for each frame of the first n_init frames, otherwise it will be deleted, which means the age for undeleted tentative track is at most 1, so there is something wrong in your question

**Comment by DenerKup** [comment]
@animebing Thanks for the point. My fail: paper matches code in this.
