### ISSUE TITLE
About freeze_model.py

### ISSUE THREAD

**Issue by sunshinezhihuo** [nwojke/deep_sort#60]
When I Generating detections using  
python tools/generate_detections.py \
    --model=resources/networks/mars-small128.pb \
    --mot_dir=./MOT16/train \
    --output_dir=./resources/detections/MOT16_train

``
have a problem:
Traceback (most recent call last):
  File "tools/generate_detections.py", line 213, in <module>
    main()
  File "tools/generate_detections.py", line 207, in main
    encoder = create_box_encoder(args.model, batch_size=32)
  File "tools/generate_detections.py", line 100, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "tools/generate_detections.py", line 86, in __init__
    assert len(self.input_var.get_shape()) == 4
  File "/home/qi/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 486, in __len__
    raise ValueError("Cannot take the length of Shape with unknown rank.")
ValueError: Cannot take the length of Shape with unknown rank. 
How to solve it? Thank you!

**Comment by nwojke** [comment]
The error seems to be due to a tensor that is loaded from the model protobuf [here](https://github.com/nwojke/deep_sort/blob/master/tools/generate_detections.py#L80). Did you try to use ``tools/freeze_model.py`` to re-generate the protobuf file with your own Python version?

**Comment by ckcraig01** [comment]
For freeze_model.py, you may have to modify two places for correct execution of generate_detection.py
(1) @ about line 155, keepdims shall be modified to keep_dims (with underline)
(2) @ about line 200:   input_var = tf.placeholder( tf.uint8, (None, 128, 64, 3), name="images")
  "None" shall be modify to a number, for e.g., "1" (i guess this is batch size?)
In addition, in generate_detection.py main function:
encoder = create_box_encoder(args.model, batch_size=32) : you may need to set your batch_size to 1 if you set it to 1 in freeze_model.py.

**Comment by sunshinezhihuo** [comment]
OK，the problem is solved,thank you
