### ISSUE TITLE
About the threshold value for cos distance of features

### ISSUE THREAD

**Issue by shuoyuanxu** [nwojke/deep_sort#61]
From the paper, the threshold value is chosen base on a separate training dataset:
![image](https://user-images.githubusercontent.com/21218812/38371533-95276d56-38e4-11e8-919b-293a5f158d69.png)
Can you please be more specific about how the threshold value is found? Is it also given in the code? Thank you!

Best Regards

Shuoyuan

**Comment by nwojke** [comment]
The dataset used to train parameters was the MOT training dataset. The value has been found by plotting histograms of cosine distances between positive pairs (two images of the same ID) and negative pairs (two images of different ID) between ground-truth tracks that could be matched in a certain time window.

This code is not in the repo. Most of the code used to write the code went into [this library](https://github.com/nwojke/pymotutils). Checkout the utility functions in [this file](https://github.com/nwojke/pymotutils/blob/master/pymotutils/application/dataset.py) but there is no single function to call for this.
