### ISSUE TITLE
Not tracking the detections

### ISSUE THREAD

**Issue by tonmoyborah** [nwojke/deep_sort#65]
I have a custom test sequence of images and their annotations. I generated the npy file with `generate.py` and now running deep sort for tracking but the rendered video has no boxes. The following snippet is what I changed in `generate.py` for reading annotations from xml files per image.

        
    detections_out = []
    rows = []
    for anno_file in os.listdir(mot_dir + '/AnnotationsOutput'):
        print("Processing %s" % anno_file)     
        image_name = anno_file.split('.')[0]
        bgr_image = cv2.imread(mot_dir + '/JPEGImagesOutput/' + image_name + '.jpg', 
                                                        cv2.IMREAD_COLOR)
        tree = ET.parse(mot_dir + '/AnnotationsOutput/' + anno_file)
        root = tree.getroot()
        for objects in root.findall('object'):
            bndbox = objects.find('bndbox')
            xmax = float(bndbox.find('xmax').text)
            xmin = float(bndbox.find('xmin').text)
            ymax = float(bndbox.find('ymax').text)
            ymin = float(bndbox.find('ymin').text)
            h = ymax - ymin
            w = xmax - xmin
            box = [xmin, ymin, h, w]
            rows.append(box)
            print(rows)
        features = encoder(bgr_image, rows, image_name)
        detections_out += [np.r_[(row, feature)] for row, feature
                           in zip(rows, features)]
    output_filename = os.path.join(output_dir, "test1.npy")
    np.save(
     output_filename, np.asarray(detections_out), allow_pickle=False)

**Comment by tonmoyborah** [comment]
Here is a debugger screenshot for your reference https://drive.google.com/file/d/12hCLez1KUhdv0CG7SQyABCDIs8fOSiTb/view?usp=sharing
Thank you!

**Comment by tonmoyborah** [comment]
Got it, the confidence score parameter was the issue.

**Comment by anzy0621** [comment]
@tonmoyborah can you please tell me how you generated the annotations(detections) for your custom detections? I'm using tensorflow faster rcnn and I just have the output detection videos and the ground truth boxes in an xml file. Is it possible to use the output object detection video to generate detections?
