### ISSUE TITLE
only got 54.9 MOTA on MOT16

### ISSUE THREAD

**Issue by nvnnghia** [nwojke/deep_sort#66]
Hi, I tried to reproduce the tracking results. I downloaded all the provided .npy files and run the code. But, I only got 54.9 MOTA on MOT16 challange. I did not change anything about the code. Do you have any idea? Thank you

**Comment by ss199302** [comment]
@nvnnghia How  do you get MOTA? I can't do this,thank you very much!

**Comment by nvnnghia** [comment]
Hi @ss199302 , You need to extract the tracking information same as MOT format. Then you submit result to https://motchallenge.net/ They will help you to calculate it. :)

**Comment by nwojke** [comment]
We might have done some minor refactoring to the code base after the submission... I think not but I am not sure anymore. The website says MOTA 61.4 so this is quite a large difference. I am not sure what is causing the difference. Can we be sure they didn't change the evaluation toolkit?

**Comment by nvnnghia** [comment]
Thank you

**Comment by ss199302** [comment]
@nvnnghia  Hello, I tried to use MOT website to evaluate the tracking results, but when I registered my account, the website item did not know what to write, and this error occurred."Email domain hotmail.com not accepted. You have either used a generic email like hotmail or 163.com, or your domain already exists in our database. Please fill out this form to request a registration."can you tell me why?thanks.

**Comment by nvnnghia** [comment]
hi @ss199302, you have to use a special email with special domain. gmail, yahoo, etc are not accepted.

**Comment by ss199302** [comment]
@nvnnghia  Can you tell me which mailbox is OK? Thank you!

**Comment by nvnnghia** [comment]
hi @ss199302  I'm not sure. I try with special email. company email, school email work for me.

**Comment by shubhamturai** [comment]
can anyone help me to derive scores on my own using py-motmetrics package by using the results file ( after running evaluate_motchallenge.py ) to get scores MOTA, P, etc.

Or If you have any other suggestion, would highly appreciate that. Thank you.

**Comment by Ujang24** [comment]
> can anyone help me to derive scores on my own using py-motmetrics package by using the results file ( after running evaluate_motchallenge.py ) to get scores MOTA, P, etc.
> 
> Or If you have any other suggestion, would highly appreciate that. Thank you.

Have you got this?

**Comment by wandyu** [comment]
> > can anyone help me to derive scores on my own using py-motmetrics package by using the results file ( after running evaluate_motchallenge.py ) to get scores MOTA, P, etc.
> > Or If you have any other suggestion, would highly appreciate that. Thank you.
> 
> Have you got this? I need the info too.

Did you solve this issue. I have a problem with the evaluation too.
