### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by tonmoyborah** [nwojke/deep_sort#67]
Hi Nwojke, I have retrained the cosine metric model from scratch on the MARS dataset for pedestrians and now plan to fine tune it on my own dataset which has 8 classes. How does fine tuning work on this network? What changes do I have to do and anything else I need to take care of?
My line of thought is that since the cosine metric model learns association, it will start learning general association parameters for all types of objects in the early layers and hence fine tuning the model for other objects should work well. Pardon my inexperience in the application part.
Thanks a lot for all the help!

**Comment by tonmoyborah** [comment]
I fine tuned the model as per my requirement, the model tracks static objects as expected but fails to track moving objects. The box colours become red during movement and it reassigns new IDs. Is there a specific parameter to avoid such behaviour? I think reducing fps might make it perform better but not better enough.

**Comment by tonmoyborah** [comment]
After a few parameter tuning, I think I have achieved good results. Specifically, maximum age was set to 30 which is way less imo. Closing this. Thanks a lot!

**Comment by MingjieLiu** [comment]
Hi @tonmoyborah 
when I retrain the cosine metric model, I meet some problem
![image](https://user-images.githubusercontent.com/16024855/40424488-bba8050a-5ed0-11e8-93af-8734eaf646cd.png)
would you help me? thank you.

**Comment by arun-kumark** [comment]
Hi @tonmoyborah
I am new to this framework.
I have assigned max_age a high value, as you said in your previous thread.
The problem is, it assigns a new ID everytime. Can you please help me, how to tune it so that for each person only a unique ID is assigned.
Please help.

thanks
