### ISSUE TITLE
Running tracker frame-by-frame (real-time)

### ISSUE THREAD

**Issue by haroonchoudery** [nwojke/deep_sort#70]
I'm attempting to implement Deep SORT into an app that will allow me to track people in a video in "real-time", meaning without having to preprocess each frame of the video prior to getting detections and then detection features. 

My question is: does the tracker need features from all frames of a video to work? Can it work by just taking the features from the previous frame?

**Comment by tonmoyborah** [comment]
Reading the paper gives me the idea that it won't be real-time/online if it needed. It justs needs the previous 3 frames to calculate the metrics imo.

**Comment by Qidian213** [comment]
I combined deep_sort and yolov3 ,it can tracking real-time use my laptop's camera

https://github.com/Qidian213/deep_sort_yolov3

**Comment by nwojke** [comment]
The tracker is able to produce output at each frame in an online fashion. Thanks for the pointer to such an implementation @Qidian213
