### ISSUE TITLE
Unable to find the implementation of Mahalanobis distance

### ISSUE THREAD

**Issue by lchunleo** [nwojke/deep_sort#72]
I reading through the paper and the code and unable to find the implementation of the Mahalanobis distance. Can advise where can i locate it?

**Comment by katerynaCh** [comment]
@lchunleo this might help you 
#42

**Comment by Phoebe-star** [comment]
do you know how to change the threshold for association admissible in the code?
![image](https://user-images.githubusercontent.com/29423761/41161186-8f3404e2-6b64-11e8-92e5-05fbb637e84f.png)

**Comment by nwojke** [comment]
The corresponding code line is [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort/linear_assignment.py#L182).
