### ISSUE TITLE
can not run generate_detections.py with new training model

### ISSUE THREAD

**Issue by MingjieLiu** [nwojke/deep_sort#74]
thank you for your sharing

I trained the model using VeRi dataset by triple_reid, however, when I copy the model including .data, .index and .meta to /resources/networks and run generate_detections.py by "python tools/generate_detections.py --model=resources/networks/checkpoint-50000 --mot_dir=./MOT/data --optput_dir=./resources/detections/MOT", it shows the error as follows:
![image](https://user-images.githubusercontent.com/16024855/40345479-4b68ae5e-5dd4-11e8-9143-bbc4ccc9ac45.png)
I cannot find the reason, would you please help me? thank you

**Comment by nwojke** [comment]
The code has been refactored to work with a frozen inference graph (see [here](https://github.com/nwojke/cosine_metric_learning#model-export)). Does this help?

**Comment by Clara85** [comment]
@MingjieLiu You will need to freeze your model into `.pb` file from your ckpt file that you trained, and then pass the name of the input and output layers when using the encoder.

**Comment by nwojke** [comment]
I am closing the issue due to inactivity. Please re-open if it remains and open issue.
