### ISSUE TITLE
A problem about the kf

### ISSUE THREAD

**Issue by otakudj** [nwojke/deep_sort#75]
Hi, in the deep sort/kalman_filter.py, function "update", line 184-185. All the equations in this function are the same as the kalman filter descibed in [Wiki](https://en.wikipedia.org/wiki/Kalman_filter) except the "new_covariance".  It, represented by P_new, in Wiki, is defined by equation P_new = (I - KH)P(I - KH) + KRK. However, your P_new = P - K(HPH + R)K. Can you tell me why you update the P_new like this? @nwojke

**Comment by nwojke** [comment]
There are different implementations of the Kalman filter which are equivalent but have different numerical properties. The one on wiki should produce the same results up to numerical accuracy. As to why we chose to do it differently I would argue with personal preference.
