### ISSUE TITLE
error running generate_directions.py and freeze_model.py

### ISSUE THREAD

**Issue by anna-grandi** [nwojke/deep_sort#80]
I ran generate_directions.py (without CUDA) and got the error message:
File "C:\Users\<username>\PycharmProjects\deep_sort\venv\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: ./resources/networks/mars-small128.pb 
; No such process
And I basically got the same problem trying tu run freeze_model.py:
InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on resources/networks/mars-small128.ckpt-68577: Not found: FindFirstFile failed for: resources/networks 
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:C

Any idea why this occurs? Using the gpu version of tensorflow doesn't seem to do any good.

**Comment by nwojke** [comment]
The error message ``Not found: FindFirstFile failed for: resources/networks`` looks to me like it is looking in a wrong place for the checkpoint files. How did you call the script?

**Comment by ChristineZhangg** [comment]
Hi, I have the almost same question:

I ran generate_directions.py and got the error message:
"tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: ./resources/networks/mars-small128.pb : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process"

And I got the same problem running freeze_model.py:
"InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./resources/networks/mars-small128.ckpt-68577: Not found: FindFirstFile failed for: ./resources/networks : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2_33/_65 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_226_save/RestoreV2_33", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
"
Can you help me fix this error? Thank you.

**Comment by anna-grandi** [comment]
Hello! Thanks for the quick reply :) the trouble was I wasn't using absolute paths for the function parameters.

**Comment by nwojke** [comment]
Interesting. Glad you found the error.

**Comment by nwojke** [comment]
@SavannahZhang Does passing an absolute path solve the problem for you too?

**Comment by pipidoudou** [comment]
I got the same error when  running freeze_model.py on Windows 10:

Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/work/chelun/tools/freeze_model.py", line 219, in <module>
    main()
  File "D:/work/chelun/tools/freeze_model.py", line 209, in main
    saver.restore(session, args.checkpoint_in)
  File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1536, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 364, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: resources/networks : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

But I ran generate_directions.py successfully.

I tried to change the path in the code to absolute path . But no matter "D:/xx/xx" or "D:\\xx\\xx", still failed.

parser.add_argument(
        "--checkpoint_in",
        default="resources/networks/mars-small128.ckpt-68577",
        help="Path to checkpoint file")
    parser.add_argument(
        "--graphdef_out",
        default="resources/networks/mars-small128.pb")

Can you help me fix this error? Thank you.

**Comment by leezisheng** [comment]
@pipidoudou  i meet the same problem ,do you fix this error ? please hlep me ,thank you
