### ISSUE TITLE
Labeling 

### ISSUE THREAD

**Issue by tungduongbk** [nwojke/deep_sort#81]
Hi all, I wanna label in each person after tracking. And remove the label after track's deleted(like track_id). When track_id is removed or still not forget!!.

Sorry for my ability English!!.

**Comment by nwojke** [comment]
Hi tungduongbk, are there any specific issues with the code base that you encountered during your experiments?

**Comment by nwojke** [comment]
I am closing the ticket. Please re-open if you have a specific problem.
