### ISSUE TITLE
long- term occlusions deep_sort_app.py

### ISSUE THREAD

**Issue by juanmanuelrq** [nwojke/deep_sort#86]
Hi, what parameter could I change to with long - term occlusions in the file 

file: deep_sort_app.py

min_confidence = 0.8,  nms_max_overlap = 1.0, min_detection_height = 0, max_cosine_distance = 0.8
max_age=30, n_init=3

What parameter should I change to increase the occlusion time?

In the next image, the vehicle with track id = 6, before the bridge had the track_id=2

![figure d33 tracker_screenshot_09 07 2018](https://user-images.githubusercontent.com/29231800/42460404-627eabac-8363-11e8-9509-93202d0a5fbb.png)

best regards

**Comment by cesarandreslopez** [comment]
@juanmanuelrq the model itself is trained on people, not vehicles, so deep sorting wouldn't be working there, just regular sorting. An option for you would be to train your own model in cars based on: https://github.com/nwojke/cosine_metric_learning

**Comment by ss199302** [comment]
@juanmanuelrq  I have the same question?  Have you solved it?

**Comment by tonmoyborah** [comment]
You can fine tune the model for vehicles or use the Veri trained version. Also max age is the number of frames. If you have a 30fps video, try setting max age to something like 150-300

**Comment by juanmanuelrq** [comment]
I have changed the max age,

but the new question that I am trying to solve is killing the trajectories when the vehicles have finished the trajectories, at this moment the new vehicles enter into the image with old trajectories.

best regards

**Comment by tonmoyborah** [comment]
That didn't happen in my case, maybe because I fine-tuned it well for my case?

**Comment by srika91** [comment]
@tonmoyborah  where did u find the Veri trained version model?

**Comment by kli017** [comment]
can you share the fine-tuned model?@tonmoyborah  Thank you!

**Comment by zhujinchao123** [comment]
can you share the fine-tuned model?@tonmoyborah Thank you!?

**Comment by wduo** [comment]
can you share the fine-tuned model?@tonmoyborah Thank you!

**Comment by nwojke** [comment]
We currently don't provide any pre-trained VeRi models, but the [cosine_metric_learning](https://github.com/nwojke/cosine_metric_learning) repository contains code in branch [feature/veri_dataset] which makes it fairly straight forward to train a model yourself.
