### ISSUE TITLE
Where can i find \lambda in the code?

### ISSUE THREAD

**Issue by antocapp** [nwojke/deep_sort#91]
Where is lambda in the code? I refer to \lambda of this equation:
![41161186-8f3404e2-6b64-11e8-92e5-05fbb637e84f](https://user-images.githubusercontent.com/26765504/43078876-eea3a924-8e8b-11e8-8d8b-25d9cb270ae9.png)

**Comment by antocapp** [comment]
Hi @VellalaVineethKumar, at the end I definitely opted for other better repositories. 

This code does not work very well, the support is very poor and the implementation of the code is very different from what is described in the article. 

I have switched my interest to a better code, which is the following repository:
https://github.com/longcw/MOTDT/

I hope this can be helpful for you.

**Comment by nwojke** [comment]
Sorry for the late reply. In case this is an open problem: The question has come up a few times already. Unfortunately, our final implementation doesn't contain any lambda at all. Instead, we have a function that invalidates the appearance-based cost according to the Kalman filter gate [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort/tracker.py#L95).

**Comment by EricThomson** [comment]
Lambda is basically set to 0, so equation 5 becomes just the right-hand-side, but then the kalman-based distance comes in with the gating. They mention on p 3 of the paper that they found lambda=0 to be good, so they used that. It seems it wouldn't be that hard to add lambda as a parameter to the tracker -- it would require using the Mahalanobis distance, which is already calculated in the code for the gating function, and  taking a linear combination of that and the distance in appearance space.

**Comment by michael-camilleri** [comment]
I implemented in my fork of the repository, in case anyone needs it (https://github.com/michael-camilleri/deep_sort)
