### ISSUE TITLE
How can I store total number of people(ID) in whole videos to text file (for final Anlysis of video)

### ISSUE THREAD

**Issue by Akhtar303nu** [nwojke/deep_sort#93]
using deep sort i want to count total number of people in whole video and total count store in txt file for final report to anlysis
note:i am using id for counting

**Comment by nwojke** [comment]
Hi Akhtar303nu, sorry for my late reply. This seems to be more of a general coding question which is out of scope of this issue tracker. If you have any specific questions about the code base, re-open the ticket.

**Comment by ykshitij** [comment]
@Akhtar303nu  How are you Using Id for people counting ? The ID printed on bounding box of each cannot be used for counting. You can see this video  https://www.bilibili.com/video/av23500163/
