### ISSUE TITLE
Request of tensorflow meta file.

### ISSUE THREAD

**Issue by prnvjb** [nwojke/deep_sort#95]
Hi,

Would you please share tensorflow meta file of deep_sort?

Thanks!!

**Comment by swearos** [comment]
@prnvjb https://github.com/nwojke/cosine_metric_learning

**Comment by nwojke** [comment]
Unfortunately, I don't have the meta file of the original model anymore. But since the network architecture code is provided ([here](https://github.com/nwojke/deep_sort/blob/master/tools/generate_detections.py)), you should be able re-generate it by loading and re-saving the model.
