### ISSUE TITLE
the accuracy degrades after  generating detections using generate_detections.py

### ISSUE THREAD

**Issue by liangzimei** [nwojke/deep_sort#98]
Hi , i run the deep_sort code on the test video (MOT16-06.mp4) directly, and second time, i generate detections as readme said, also run the MOT16-06.mp4.  the former's accuracy is higher, is it the problem of detection phase?  the size of MOT16-06.npy i generated (8M) is different from [here ](https://owncloud.uni-koblenz.de/owncloud/s/f9JB0Jr7f3zzqs8)（11M）. They both use the mars-small128 pretrained model after all. thanks in advance……

**Comment by nwojke** [comment]
Hi liangzimei,

sorry for the late reply. This behavior is expected. In the [README section](https://github.com/nwojke/deep_sort#generating-detections) that you are refering to, we explain the feature generation script on standard MOT benchmark detections. Contrary, we used a stronger detector in our experiments (the ones that we provided). As you can see, detection quality has a strong impact on tracking performance.
